version: "3.8"

services:
  excel-merge-api:
    container_name: excel-merge-api
    image: excel-merge-api
    build: ./
    volumes:
      - ./src:/app/src
    env_file:
    - .env
    ports:
      - 5001:5001