version: "3.8"

services:
  excel-merge-api:
    container_name: excel-merge-api
    image: excel-merge-api
    build: ./
    volumes:
      - ./:/app
    env_file:
    - .env
    ports:
      - 5000:5000